//
//  ListGistsWorker.swift
//  Gister
//
//  Created by Raymond Law on 10/12/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListGistsWorker
{
  var gistAPI: GistAPIProtocol = GistAPI()
  
  func fetch(completionHandler: @escaping ([Gist]) -> Void)
  {
    gistAPI.fetch { (gists) in
      completionHandler(gists)
    }
  }
}
