//
//  ListGistsWorker.swift
//  Gister
//
//  Created by Raymond Law on 10/12/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListGistsWorkerDelegate
{
  func listGistsWorker(listGistsWorker: ListGistsWorker, didFetchGists gists: [Gist])
}

class ListGistsWorker: GistAPIDelegate
{
  var gistAPI: GistAPIProtocol = GistAPI()
  var delegate: ListGistsWorkerDelegate?
  
  // MARK: Block implementation
  
  func fetch(completionHandler: @escaping ([Gist]) -> Void)
  {
    gistAPI.fetch { (gists) in
      completionHandler(gists)
    }
  }
  
  // MARK: Delegate implementation
  
  func fetch()
  {
    gistAPI.delegate = self
    gistAPI.fetch()
  }
  
  func gistAPI(gistAPI: GistAPIProtocol, didFetchGists gists: [Gist])
  {
    delegate?.listGistsWorker(listGistsWorker: self, didFetchGists: gists)
  }
}
