//
//  ListGistsModels.swift
//  Gister
//
//  Created by Raymond Law on 10/12/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListGists
{
  // MARK: Use cases
  
  enum FetchGists
  {
    struct Request
    {
    }
    struct Response
    {
      var gists: [Gist]
    }
    struct ViewModel
    {
      struct DisplayedGist
      {
        var login: String
        var url: String
        var filename: String
        var filetype: String
      }
      var displayedGists: [DisplayedGist]
    }
  }
}
