//
//  ListGistsPresenterTests.swift
//  Gister
//
//  Created by Raymond Law on 10/12/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Gister
import XCTest

class ListGistsPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListGistsPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListGistsPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListGistsPresenter()
  {
    sut = ListGistsPresenter()
  }
  
  // MARK: Test doubles
  
  class ListGistsDisplayLogicSpy: ListGistsDisplayLogic
  {
    var displayFetchedGistsCalled = false
    var displayFetchedGistsViewModel: ListGists.FetchGists.ViewModel!
    
    func displayFetchedGists(viewModel: ListGists.FetchGists.ViewModel)
    {
      displayFetchedGistsCalled = true
      displayFetchedGistsViewModel = viewModel
    }
  }
  
  // MARK: Tests
  
  func testPresentFetchedGistsShouldAskViewControllerToDisplayGists()
  {
    // Given
    let listGistsDisplayLogicSpy = ListGistsDisplayLogicSpy()
    sut.viewController = listGistsDisplayLogicSpy
    
    // When
    let gists = [Seeds.Gists.text, Seeds.Gists.html]
    let response = ListGists.FetchGists.Response(gists: gists)
    sut.presentFetchedGists(response: response)
    
    // Then
    let expectedGists = [Seeds.DisplayedGists.text, Seeds.DisplayedGists.html]
    let actualGists = listGistsDisplayLogicSpy.displayFetchedGistsViewModel.displayedGists
    XCTAssertTrue(listGistsDisplayLogicSpy.displayFetchedGistsCalled, "presentFetchedGists(response:) should ask the view controller to display gists")
    XCTAssertEqual(actualGists, expectedGists, "presentFetchedGists(response:) should display the correct gists")
  }
}
