//
//  ListGistsWorkerTests.swift
//  Gister
//
//  Created by Raymond Law on 10/12/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Gister
import XCTest

class ListGistsWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListGistsWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListGistsWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListGistsWorker()
  {
    sut = ListGistsWorker()
  }
  
  // MARK: Test doubles
  
  class GistAPISpy: GistAPIProtocol
  {
    var fetchCalled = false
    
    func fetch(completionHandler: @escaping ([Gist]) -> Void)
    {
      fetchCalled = true
    }
  }
  
  // MARK: Tests
  
  func testFetchShouldAskGistAPIToFetchGists()
  {
    // Given
    let gistAPISpy = GistAPISpy()
    sut.gistAPI = gistAPISpy
    
    // When
    sut.fetch { (gists) in }
    
    // Then
    XCTAssertTrue(gistAPISpy.fetchCalled, "fetch(completionHandler:) should ask Gist API to fetch gists")
  }
}
