//
//  ListGistsInteractorTests.swift
//  Gister
//
//  Created by Raymond Law on 10/12/17.
//  Copyright (c) 2017 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Gister
import XCTest

class ListGistsInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ListGistsInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupListGistsInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupListGistsInteractor()
  {
    sut = ListGistsInteractor()
  }
  
  // MARK: Test doubles
  
  class ListGistsWorkerSpy: ListGistsWorker
  {
    var fetchCalled = false
    
    override func fetch(completionHandler: @escaping ([Gist]) -> Void)
    {
      let gists = [Seeds.Gists.text, Seeds.Gists.html]
      fetchCalled = true
      completionHandler(gists)
    }
  }
  
  class ListGistsPresentationLogicSpy: ListGistsPresentationLogic
  {
    var presentFetchedGistsCalled = false
    
    func presentFetchedGists(response: ListGists.FetchGists.Response)
    {
      presentFetchedGistsCalled = true
    }
  }
  
  // MARK: Tests
  
  func testFetchGistsShouldAskWorkerToFetchGists()
  {
    // Given
    let listGistsWorkerSpy = ListGistsWorkerSpy()
    sut.listGistsWorker = listGistsWorkerSpy
    let request = ListGists.FetchGists.Request()
    
    // When
    sut.fetchGists(request: request)
    
    // Then
    XCTAssertTrue(listGistsWorkerSpy.fetchCalled, "fetchGists(request:) should ask the worker to fetch gists")
  }
  
  func testFetchGistsShouldAskPresenterToFormatGists()
  {
    // Given
    let listGistsWorkerSpy = ListGistsWorkerSpy()
    sut.listGistsWorker = listGistsWorkerSpy
    let listGistsPresentationLogicSpy = ListGistsPresentationLogicSpy()
    sut.presenter = listGistsPresentationLogicSpy
    let request = ListGists.FetchGists.Request()
    
    // When
    sut.fetchGists(request: request)
    
    // Then
    XCTAssertTrue(listGistsPresentationLogicSpy.presentFetchedGistsCalled, "fetchGists(request:) should ask the presenter to format gists")
  }
}
